[Providers:openai]
Type = openai
Endpoint = http://127.0.0.1:11434/v1

[Providers:anthropic]
Type = anthropic
; Endpoint = http://127.0.1:11434

[Providers:ollama]
Type = ollama
Endpoint = http://127.0.0.1:11434

[Agents:chat]
Description = A specialized agent for chat. Use this agent to have a conversation with the model.
SystemPrompt = You are a helpful assistant. You may use tools to answer questions.
Model = claude-sonnet-5
Provider = anthropic
MaxOutputTokens = 4096
; Model = qwen3:4b-instruct-2507-q4_K_M
; Provider = ollama
# AutoApproveTools:0 = filesystem_read*
# DefaultToolPolicy = deny
Mcp:0 = filesystem
Mcp:1 = test
# Mcp:1 = everything

[Agents:code-writer]
Description = A specialized agent writing code. Use this agent to write any code.
SystemPrompt = You are a code writer. You will be given a task to write code. You will write the code in the specified programming language. You will not write any explanations or comments. You will only write the code. You will use tools to write code. You will not output it in chat. After you finish, you will write a brief summary of your changes.
Model = devstral-small-2:24b-instruct-2512-q4_K_M
Provider = openai
DefaultToolPolicy = allow
Mcp:0 = filesystem
# Mcp:1 = everything

[Agents:code-reviewer]
Description = A specialized agent reviewing code. Use this agent to review code.
SystemPrompt = You are a code reviewer. You will be given a task to review code. You will review the code and provide feedback. You will not output it in chat. After you finish reviewing, you will write a complete list of all the issues you found in the code. You will also provide suggestions for improvement.
Model = devstral-small-2:24b-instruct-2512-q4_K
Provider = ollama
DefaultToolPolicy = allow
Mcp:0 = filesystem

[Mcp:filesystem]
Command = npx
Args:0 = -y
Args:1 = @modelcontextprotocol/server-filesystem
Args:2 = /home/kuba/repos/agent-mcp-test
# Args:2 = /tmp

[Mcp:everything]
Command = npx
Args:0 = -y
Args:1 = @modelcontextprotocol/server-everything

[Mcp:test]
Endpoint = http://127.0.0.1:5000

# [Mcp:agent-mcp]
# Command = /nix/store/k6brwx3cs63lvrwd6ni0hypc9jcgapbk-dotnet-sdk-wrapped-10.0.301/bin/dotnet
# Args:0 = /home/kuba/repos/agent-mcp/AgentMcp/bin/Debug/net10.0/AgentMcp.dll
# Args:1 = --contentRoot
# Args:2 = /home/kuba/repos/agent-mcp/AgentMcp/bin/Debug/net10.0
